# Generated by Django 5.0.6 on 2024-06-03 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='SecondName',
            new_name='LastName',
        ),
    ]
